### ISSUE TITLE
Results for m1 ultra (48 core gpu)

### ISSUE THREAD

**Issue by machineko** [lucadiliello/pytorch-apple-silicon-benchmarks#3]
I run your script on my machine for extra results 😄 

Im not sure if MPS on pytorch give sane results all my pretrained models are just full of trash outputs right now (not even once i got result compariable with coreml/pytorch cpu so if you have time you should also make some check for that [compare diff in cpu vs mps version for example] )

Here are the results for inference on m1 ultra

<img width="1086" alt="Zrzut ekranu 2022-06-4 o 15 29 51" src="https://user-images.githubusercontent.com/42299606/172003309-d80c2d08-7858-4bdc-8638-4e0c751b56ec.png">
<img width="1086" alt="Zrzut ekranu 2022-06-4 o 15 30 31" src="https://user-images.githubusercontent.com/42299606/172003311-5d0d5784-f901-47dc-a02c-b40368c7eee3.png">
<img width="1086" alt="Zrzut ekranu 2022-06-4 o 15 32 20" src="https://user-images.githubusercontent.com/42299606/172003313-dc845b86-95f9-486e-84d0-fa18c5570856.png">
<img width="1086" alt="Zrzut ekranu 2022-06-4 o 15 33 09" src="https://user-images.githubusercontent.com/42299606/172003315-ff3635b3-eef9-49e9-9736-af801ea44489.png">
<img width="1086" alt="Zrzut ekranu 2022-06-4 o 15 35 02" src="https://user-images.githubusercontent.com/42299606/172003317-56b327c5-9bb6-4b41-bbca-29832052c0b1.png">
<img width="1086" alt="Zrzut ekranu 2022-06-4 o 15 41 05" src="https://user-images.githubusercontent.com/42299606/172003319-634e670e-e27a-4f65-b954-dba2558c6ee7.png">

**Comment by lucadiliello** [comment]
Thank you! How much RAM has your system? Version of pytorch?

**Comment by machineko** [comment]
torch->'1.13.0.dev20220604
neofetch
<img width="301" alt="Zrzut ekranu 2022-06-4 o 20 06 31" src="https://user-images.githubusercontent.com/42299606/172020041-13c8d78b-96c0-470a-bd09-c53fea60f8e4.png">
